steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/landing-page-ssb-recruitment", "."]

  # Push Docker image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/landing-page-ssb-recruitment"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "run",
        "deploy",
        "landing-page-ssb-recruitment",
        "--image=gcr.io/$PROJECT_ID/landing-page-ssb-recruitment",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "512Mi",
        "--concurrency",
        "80",
        "--timeout",
        "300",
        "--max-instances",
        "5",
        "--min-instances",
        "0",
        "--containerport",
        "8080",
      ]
images:
  - gcr.io/$PROJECT_ID/landing-page-ssb-recruitment
